services:
  rust:
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace
    env_file:
      - .env
    ports:
      - 50051:50051

volumes:
  rust-target: